// components/layout.js

import Header from "./Header";
import Footer from "./Footer";
import Head from "next/head";

export default function Layout({ children }) {
  return (
    <div className="content">
      <Head>
        <title>Test Remote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/td.ico" />
      </Head>

      <Header />
      <main>{children}</main>
      <Footer />
    </div>
  );
}
